# Specifying all dtypes to maximize  efficiency
dtypes = {'Service Transaction ID':'string',
            'Sale ID':'string',
            'Sale Date':'string',
            'Sale Item ID':'string',
            'Sale Facility Country':'string',
            'Sale Day':'string',
            'Sale Facility':'string',
            'Sale Facility ID':'string',
            'Mph Arma ID':'string',
            'Customer Type':'string',
            'Vdl Drug ID':'string',
            'Vdl Drug Display Name':'string',
            'Unit Selling Price Local':'float32',
            'Unit Selling Price Usd':'float32',
            'Quantity In Units':'float32',
            'Quantity In Packs':'float32',
            'Sale Item Selling Price Local':'float32',
            'Sale Item Selling Price Usd':'float32',
            'Unit Vm I Cost Price Local':'float32',
            'Sale Item Vm I Cost Price Local':'float32',
            'Sale Item Vm I Cost Price Usd':'float32',
            'Sale Item Vm I Margin Local':'float32',
            'Sale Item Vm I Margin Usd':'float32',
            'Unit Cost Price Local':'float32',
            'Unit Cost Price Usd':'float32',
            'Sale Item Cost Price Local':'float32',
            'Sale Item Cost Price Usd':'float32',
            'Sale Item Margin Local':'float32',
            'Sale Item Margin Usd':'float32',
            'Payment Method Type':'string',
            'Payment Timing Type':'string',
            'Product ID':'string',
            'Product Name':'string',
            'Product Alias ID':'string',
            'Product Alias Name':'string',
            'Patient Facility ID':'string',
            'Patient Facility Name':'string',
            'Patient Risk Tier Type':'string',
            'Corporate Facility Name':'string',
            'Customer Corporate Type':'string',
            'Facility Country':'string',
            'Sale Date Local':'string',
            'Item Category':'string',
            'Item Sub Category':'string',
            'Insurance Pay Or':'string',
            'Product Source':'string',
            'Vat Local (for The It Em)':'float32',
            'Vat Usd (for The It Em)':'float32',
            'Is Manual':'string',
            'Receipt ID':'string',
            'How Its Sold':'string',
            'Is Off Formula Ry':'string',
            'Mv Drug Abc → Country':'string',
            'Mv Drug Abc → Class':'string',
            'Mv Drug Abc → Class By Value':'string',
            'Mv Drug Abc → Class By Quantity':'string',
            'Mv Drug Abc → Class By Transaction Count':'string',
            'Mv Drug Abc → Class By Margin':'string'
            }


relevant_cols = ['Sale Date']
